import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Copy, CreditCard, ExternalLink, Globe, Mail, Rocket } from "lucide-react";
import { systemControlsApi } from "../api/system-controls";
import { queryKeys } from "../lib/queryKeys";
import { Button } from "./ui/button";
import { ExecutionStatusBadge } from "./ExecutionStatusBadge";
import { extractEvidence, formatRelativeTime, toTitleCase } from "../lib/execution-feed";

interface OutputEvidencePanelProps {
  companyId: string;
}

function iconForType(type: "reddit_post" | "deployment" | "checkout" | "email") {
  if (type === "reddit_post") return Globe;
  if (type === "deployment") return Rocket;
  if (type === "checkout") return CreditCard;
  return Mail;
}

export function OutputEvidencePanel({ companyId }: OutputEvidencePanelProps) {
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const evidenceQuery = useQuery({
    queryKey: queryKeys.executionFeed(companyId, "all", "all", 180),
    queryFn: () => systemControlsApi.getExecutionFeed(companyId, { limit: 180 }),
    enabled: !!companyId,
    refetchInterval: 8_000,
  });

  const evidenceRows = useMemo(() => {
    const events = evidenceQuery.data ?? [];
    const rows = events
      .map((event) => {
        const evidence = extractEvidence(event);
        const url = evidence?.url ?? null;
        if (!evidence || !url) return null;
        return {
          id: event.id,
          createdAt: event.createdAt,
          status: event.status,
          action: event.action,
          decisionId: event.decisionId,
          artifactId: typeof event.details.artifactId === "string" ? event.details.artifactId : null,
          artifactMetrics:
            event.details.artifactMetrics && typeof event.details.artifactMetrics === "object"
              ? (event.details.artifactMetrics as { clicks?: number; conversions?: number; revenueCents?: number })
              : null,
          evidence,
          url,
        };
      })
      .filter((row): row is NonNullable<typeof row> => row !== null);

    const dedup = new Set<string>();
    return rows.filter((row) => {
      const urlKey = row.evidence.url ?? "no-url";
      const key = `${row.evidence.type}:${urlKey}:${row.action}`;
      if (dedup.has(key)) return false;
      dedup.add(key);
      return true;
    });
  }, [evidenceQuery.data]);

  return (
    <section className="rounded-xl border border-border bg-card p-4 shadow-sm">
      <div className="flex items-center justify-between gap-2">
        <div>
          <h2 className="text-sm font-semibold text-foreground">Real World Output</h2>
          <p className="text-xs text-muted-foreground">Proof artifacts generated by your autonomous system.</p>
        </div>
        <span className="text-xs text-muted-foreground">{evidenceRows.length} artifacts</span>
      </div>

      <div className="mt-3 space-y-2">
        {evidenceQuery.isLoading && evidenceRows.length === 0 ? (
          <div className="rounded-md border border-dashed border-border px-3 py-5 text-sm text-muted-foreground">
            Loading output evidence...
          </div>
        ) : evidenceRows.length === 0 ? (
          <div className="rounded-md border border-dashed border-border px-3 py-5 text-sm text-muted-foreground">
            No output artifacts yet. Run a cycle to generate publishable proof.
          </div>
        ) : (
          evidenceRows.slice(0, 16).map((row) => {
            const Icon = iconForType(row.evidence.type);
            return (
              <article key={row.id} className="rounded-md border border-border px-3 py-3">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-start gap-2">
                    <div className="mt-0.5 rounded-md bg-muted p-1.5 text-muted-foreground">
                      <Icon className="h-3.5 w-3.5" />
                    </div>
                    <div>
                      <p className="text-xs uppercase tracking-wide text-muted-foreground">{row.evidence.label}</p>
                      <p className="text-sm font-medium text-foreground">{row.evidence.title}</p>
                      <p className="mt-0.5 text-xs text-muted-foreground">{toTitleCase(row.action)}</p>
                    </div>
                  </div>
                  <ExecutionStatusBadge status={row.status} />
                </div>

                <a
                  href={row.url}
                  target="_blank"
                  rel="noreferrer"
                  className="mt-2 block truncate text-sm text-primary hover:underline"
                >
                  {row.url}
                </a>

                <div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground">
                  <span>Time: {formatRelativeTime(row.createdAt)}</span>
                  <span>
                    clicks {Math.max(0, Number(row.artifactMetrics?.clicks ?? 0))}
                    {" · "}
                    conv {Math.max(0, Number(row.artifactMetrics?.conversions ?? 0))}
                    {" · "}
                    rev ${((Math.max(0, Number(row.artifactMetrics?.revenueCents ?? 0))) / 100).toFixed(2)}
                  </span>
                  {row.decisionId ? <span>decision {row.decisionId.slice(0, 8)}</span> : null}
                  <div className="flex items-center gap-1.5">
                    <>
                      <Button asChild size="sm" variant="outline" className="h-7 px-2 text-xs">
                        <a href={row.url} target="_blank" rel="noreferrer">
                          <ExternalLink className="mr-1 h-3 w-3" />
                          Open
                        </a>
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-7 px-2 text-xs"
                        onClick={async () => {
                          try {
                            await navigator.clipboard.writeText(row.url);
                            setCopiedId(row.id);
                            setTimeout(() => setCopiedId((current) => (current === row.id ? null : current)), 1400);
                          } catch {
                            // Ignore clipboard failures in restricted environments.
                          }
                        }}
                      >
                        <Copy className="mr-1 h-3 w-3" />
                        {copiedId === row.id ? "Copied" : "Copy"}
                      </Button>
                    </>
                  </div>
                </div>
              </article>
            );
          })
        )}
      </div>
    </section>
  );
}
