import { pgTable, uuid, text, timestamp, jsonb, index } from "drizzle-orm/pg-core";
import { companies } from "./companies.js";

/** Strategy plans generated by the planning engine */
export const strategyPlans = pgTable(
  "strategy_plans",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    goalId: uuid("goal_id"),
    analysis: jsonb("analysis").notNull(), // snapshot of state at planning time
    generatedTasks: jsonb("generated_tasks").notNull(), // array of task definitions
    status: text("status").notNull().default("pending"), // pending | applied | rejected
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyIdx: index("strategy_plans_company_idx").on(table.companyId),
  }),
);
